# Generated by Django 5.2.7 on 2026-09-10 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id_alter_savedevent_id_and_more'),
        ('tickets', '0003_alter_attendeeticket_id_alter_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_assigned_seating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seating_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='Main Hall', max_length=100)),
                ('row', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Temporarily Reserved'), ('booked', 'Booked / Sold'), ('blocked', 'Blocked / Unavailable')], default='available', max_length=20)),
                ('is_accessible', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_seats', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='tickets.order')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seat', to='tickets.attendeeticket')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.tickettier')),
            ],
            options={
                'ordering': ['row', 'seat_number'],
                'unique_together': {('event', 'section_name', 'row', 'seat_number')},
            },
        ),
    ]
