# Generated by Django 5.2.7 on 2026-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventcomment_commentlike_eventlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.TextField(blank=True),
        ),
    ]
