# Generated by Django 6.1 on 2026-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='role_title',
            field=models.CharField(blank=True, default='Stage Coordinator', help_text='Designation or gate responsibility title for this event.', max_length=100),
        ),
    ]
