# Generated by Django 6.1 on 2026-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventstaff_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_ticket_transfers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_refund_cancelled_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pass_platform_fee_to_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='require_attendee_phone',
            field=models.BooleanField(default=True),
        ),
    ]
