# Generated by Django 6.1 on 2026-09-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_allow_ticket_transfers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='events/banners/'),
        ),
    ]
