# Generated by Django 6.1 on 2026-09-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_cta_text',
            field=models.CharField(blank=True, default='Book Passes', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='is_banner_hero',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recommendation_badge',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Featured Spotlight', max_length=100)),
                ('badge', models.CharField(blank=True, default='Spotlight', max_length=100)),
                ('banner_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='banners/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('cta_text', models.CharField(default='Explore Event', max_length=50)),
                ('target_url', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_banners', to='events.event')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
