# Generated by Django 6.1 on 2026-09-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_admin_notes_event_banner_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('past', 'Past / Archived'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='published', max_length=20),
        ),
    ]
