# Generated by Django 6.1 on 2026-10-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionalBanner',
        ),
    ]
