# Generated by Django 6.1 on 2026-09-02 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Attendee'), ('manager', 'Organizer')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Nexus Productions Studio', max_length=255)),
                ('handle', models.SlugField(blank=True, max_length=100, unique=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('pass_platform_fee_to_buyer', models.BooleanField(default=True)),
                ('allow_ticket_transfers', models.BooleanField(default=True)),
                ('require_attendee_phone', models.BooleanField(default=True)),
                ('auto_refund_cancelled_events', models.BooleanField(default=True)),
                ('instant_sale_alerts', models.BooleanField(default=True)),
                ('daily_summary_digest', models.BooleanField(default=True)),
                ('payout_disbursement_email', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('holder_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(default='Direct Settlement (Current A/C)', max_length=100)),
                ('status', models.CharField(choices=[('Primary', 'Primary'), ('Verified', 'Verified')], default='Verified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
