# Generated by Django 6.1 on 2026-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organizerprofile_id_alter_settlementaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementaccount',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settlementaccount',
            name='method_type',
            field=models.CharField(choices=[('paypal', 'PayPal Account'), ('bank', 'Direct Bank Deposit')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='settlementaccount',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='settlementaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settlementaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settlementaccount',
            name='account_type',
            field=models.CharField(default='Direct Settlement', max_length=100),
        ),
        migrations.AlterField(
            model_name='settlementaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settlementaccount',
            name='holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
