# Generated by Django 6.1 on 2026-09-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_settlementaccount_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, default='Stage Coordinator', max_length=100)),
                ('default_can_view_attendees', models.BooleanField(default=True, help_text='Default permission: allows viewing guest list.')),
                ('default_can_check_in', models.BooleanField(default=True, help_text='Default permission: allows scanning and checking in tickets at the gate.')),
                ('default_can_edit_attendees', models.BooleanField(default=False, help_text='Default permission: allows modifying attendee notes/details.')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_staff_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organizer', 'user')},
            },
        ),
    ]
