# Generated by Django 6.1 on 2026-09-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_avatar_url_user_bio_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Attendee'), ('manager', 'Organizer'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
