# Generated by Django 6.1 on 2026-09-02 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_created_at_user_full_name_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_deducted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_disbursed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utr_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('Pending', 'Pending')], default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('settlement_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='accounts.settlementaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
