# Generated by Django 6.1 on 2026-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_alter_payout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='destination_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='method_type',
            field=models.CharField(default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='payout',
            name='paypal_batch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payout',
            name='paypal_payout_item_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=20),
        ),
    ]
