# Generated by Django 6.1 on 2026-09-29 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0012_alter_event_title'),
        ('tickets', '0004_order_paypal_capture_id_order_paypal_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WELCOME', 'Welcome to Evento'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('ORDER_PLACED', 'Order Placed'), ('TICKET_ISSUED', 'Ticket Issued'), ('PAYMENT_FAILED', 'Payment Failed'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_COMMENT_REPLIED', 'Comment Replied'), ('TICKET_SOLD', 'Ticket Sold'), ('EVENT_SOLD_OUT', 'Event Sold Out'), ('EVENT_LOW_INVENTORY', 'Low Ticket Inventory'), ('EVENT_PUBLISHED', 'Event Published'), ('EVENT_COMMENT_RECEIVED', 'New Event Comment'), ('PAYOUT_DISBURSED', 'Payout Disbursed'), ('PAYOUT_FAILED', 'Payout Failed'), ('ORGANIZER_PROFILE_ACTIVATED', 'Organizer Profile Activated')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.event')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.attendeeticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recip_unread_idx'), models.Index(fields=['recipient', '-created_at'], name='notif_recip_created_idx')],
            },
        ),
    ]
